export const devices = [
  {
    id: "D001",
    type: "Heart Monitor",
    facility: "Apollo Hospital",
    status: "Online",
    battery: 85,
    lastServiceDate: "2024-12-01",
    amcStatus: "AMC",
  },
  {
    id: "D002",
    type: "Ventilator",
    facility: "Fortis Hospital",
    status: "Offline",
    battery: 60,
    lastServiceDate: "2024-11-20",
    amcStatus: "Non-AMC",
  },
  {
    id: "D003",
    type: "ECG Machine",
    facility: "Max Healthcare",
    status: "Online",
    battery: 78,
    lastServiceDate: "2025-01-10",
    amcStatus: "AMC",
  },
  {
    id: "D004",
    type: "Defibrillator",
    facility: "AIIMS",
    status: "Online",
    battery: 92,
    lastServiceDate: "2024-10-15",
    amcStatus: "AMC",
  },
  {
    id: "D005",
    type: "Infusion Pump",
    facility: "Medanta",
    status: "Offline",
    battery: 35,
    lastServiceDate: "2024-08-05",
    amcStatus: "Non-AMC",
  },
  {
    id: "D006",
    type: "Patient Monitor",
    facility: "Lilavati Hospital",
    status: "Online",
    battery: 88,
    lastServiceDate: "2025-02-01",
    amcStatus: "AMC",
  },
  {
    id: "D007",
    type: "Oxygen Concentrator",
    facility: "Nanavati Hospital",
    status: "Online",
    battery: 67,
    lastServiceDate: "2024-09-17",
    amcStatus: "AMC",
  },
  {
    id: "D008",
    type: "X-Ray Machine",
    facility: "Kokilaben Hospital",
    status: "Offline",
    battery: 40,
    lastServiceDate: "2024-07-11",
    amcStatus: "Non-AMC",
  },
  {
    id: "D009",
    type: "MRI Scanner",
    facility: "Ruby Hall Clinic",
    status: "Online",
    battery: 95,
    lastServiceDate: "2025-01-25",
    amcStatus: "AMC",
  },
  {
    id: "D010",
    type: "CT Scanner",
    facility: "Saket City Hospital",
    status: "Offline",
    battery: 55,
    lastServiceDate: "2024-11-03",
    amcStatus: "AMC",
  },
  {
    id: "D011",
    type: "Ultrasound Machine",
    facility: "Sir Ganga Ram Hospital",
    status: "Online",
    battery: 72,
    lastServiceDate: "2025-03-02",
    amcStatus: "AMC",
  },
  {
    id: "D012",
    type: "Blood Pressure Monitor",
    facility: "Apollo Clinic",
    status: "Offline",
    battery: 48,
    lastServiceDate: "2024-06-25",
    amcStatus: "Non-AMC",
  },
  {
    id: "D013",
    type: "Glucose Meter",
    facility: "Cloudnine Hospital",
    status: "Online",
    battery: 80,
    lastServiceDate: "2024-12-15",
    amcStatus: "AMC",
  },
  {
    id: "D014",
    type: "Suction Machine",
    facility: "Columbia Asia Hospital",
    status: "Offline",
    battery: 33,
    lastServiceDate: "2024-10-30",
    amcStatus: "Non-AMC",
  },
  {
    id: "D015",
    type: "Dialysis Machine",
    facility: "Wockhardt Hospital",
    status: "Online",
    battery: 89,
    lastServiceDate: "2024-09-12",
    amcStatus: "AMC",
  },
  {
    id: "D016",
    type: "EEG Machine",
    facility: "Manipal Hospital",
    status: "Online",
    battery: 70,
    lastServiceDate: "2025-02-19",
    amcStatus: "AMC",
  },
  {
    id: "D017",
    type: "Thermometer",
    facility: "Hinduja Hospital",
    status: "Offline",
    battery: 20,
    lastServiceDate: "2024-07-01",
    amcStatus: "Non-AMC",
  },
  {
    id: "D018",
    type: "Nebulizer",
    facility: "Dr. L.H. Hiranandani Hospital",
    status: "Online",
    battery: 76,
    lastServiceDate: "2025-01-05",
    amcStatus: "AMC",
  },
  {
    id: "D019",
    type: "Anesthesia Machine",
    facility: "Tata Memorial Hospital",
    status: "Online",
    battery: 90,
    lastServiceDate: "2024-11-28",
    amcStatus: "AMC",
  },
  {
    id: "D020",
    type: "Pulse Oximeter",
    facility: "Care Hospitals",
    status: "Offline",
    battery: 52,
    lastServiceDate: "2024-08-18",
    amcStatus: "Non-AMC",
  },
];
